#:schema https://mise.jdx.dev/schema/mise.json 

[tools]
# global tool versions go here
# you can set these with `mise use -g`
lua = "latest"
dart = "latest"
flutter = "latest"
node = "latest"
python = "3.12.2"
usage = "latest"
npm = "latest"
# python = "latest"


[settings]
env_file = '.env'
experimental = true
# configure messages displayed when entering directories with config files
# status = { missing_tools = "if_other_versions_installed", show_env = true, show_tools = true }
