#!/bin/zsh

local file_name=$1
local max_number="00"
local current_dir=$(basename "$PWD")


#Check id praxis dir is empty
_check_praxis_dir_is_empty() {
    setopt nullglob
    local dirpaths=( "$PWD"/*/ )
    for dir in "${dirpaths[@]}"; do
        local temp=$(basename "$dir")
        if [[ $temp =~ [0-9][0-9]_* ]]; then
            echo "Praxis pattern found"
            return 0
        fi
    done
    return 1
}

# Check if the current directory is praxis
_check_if_praxis_dir() {
    if [[ "$current_dir" == "praxis" ]]; then
        return 0
    else
        return 1
    fi
}


# Find the last directory number prefix in the praxis directory
_find_last_dir() {
    setopt nullglob
    local dirp=( "$PWD"/*/ )
    # echo $dirp
    local pattern='([0-9]{2})_'
    local count=0
    for dir in "${dirp[@]}"; do
        local temp=$(basename "$dir")
        [[ $temp =~ $pattern ]] && matched="${match[1]}"
        # echo $matched
        local num=$((matched))
        # echo $num
        if (( num > count )); then
            count=$((num))
            # return $count
            # echo $count
        fi
    done
    return $count
}

_increment_number_with_pad() {
    local num=$1
    local num_incr=$((num+1))
    if (( num_incr > 0)) && (( num_incr < 10 )); then
        echo "0$num_incr"
    else
        echo "$num_incr"
    fi
}

create-c-project() {
    echo $PWD
    # check if the present directory name is "praxis"
    # Get the base name of the current directory
    if _check_if_praxis_dir; then
        # echo "You are in the praxis directory"
        # Check if the praxis directory is empty
        _check_praxis_dir_is_empty
        local empty=$? # capture the return value of the function
        if [[ $empty -eq 0 ]]; then
            # echo "The praxis directory is not empty"
            _find_last_dir
            local count=$?
            # echo $count
            local file_num=$(_increment_number_with_pad $count)
            # echo $file_num
            local current_filename="${file_num}_${file_name}"
            # echo $current_filename
            local current_path="${PWD}/${current_filename}"
            # echo $current_path
            _create_dirs $current_path
        else
            # echo "The praxis directory is empty"
            local current_filename="00_${file_name}"
            local current_path="${PWD}/${current_filename}"
            # echo $current_path
            _create_dirs $current_path
        fi
    else
        # echo "You are not in the praxis directory"
        _create_dirs $file_name
    fi
}

_create_dirs() {
# Create a C project with a main.c file
        mkdir -p "$1" && cd "$1" || return 1
        mkdir -p src include bin 

        # get template from a c_prog.c file in $Home/dotfiles/template directory to main.c
        cat "$HOME/dotfiles/templates/c_header.c" > src/main.c
        cat "$HOME/dotfiles/templates/c_prog.c" >> src/main.c

        # create a justfile
        cat "$HOME/dotfiles/templates/c_justfile" > justfile


        # create a .gitignore file
        cat "$HOME/dotfiles/templates/c_gitignore" > .gitignore
        # create a README.md file
        echo "# $1" > README.md
        # git init
        git init
    }

#create-c-project $file_name
