[manager]
linemode = "size"
show_hidden = true
sort_by = "natural"

[preview]
tab_size = 2
max_width = 1000
max_height = 1000


[opener]
edit = [
  { run = '${EDITOR:=nvim} "$@"', desc = "$EDITOR", block = true, for = "unix" },
  { run = 'code "%*"', orphan = true, for = "windows" },
  { run = 'nvim "$@"', block = true },
]
reveal = [
  { run = 'xdg-open "$(dirname "$1")"', desc = "Reveal", for = "linux" },
  { run = 'open -R "$1"', desc = "Reveal", for = "macos" },
  { run = 'explorer /select,"%1"', orphan = true, desc = "Reveal", for = "windows" },
  { run = '''exiftool "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show EXIF", for = "unix" },
]
play = [
  { run = 'mpv "$@"', orphan = true, for = "unix" },
  { run = 'mpv --force-window %*', orphan = true, for = "windows" },
]
extract = [
  { run = 'ouch d -y "%*"', desc = "Extract here with ouch", for = "windows" },
  { run = 'ouch d -y "$@"', desc = "Extract here with ouch", for = "unix" },
]
open = [
  { run = 'xdg-open "$@"', desc = "Open", for = "linux" },
  { run = 'start "" "%1"', orphan = true, desc = "Open", for = "windows" },
]

[editor]
default = "krita"

[open]
rules = [
  # Media
  { mime = "{audio,video}/*", use = [ "play", "reveal" ] },
  # Text
  { mime = "text/*", use = ["edit", "reveal"] },
  # Image
  { mime = "image/*", use = ["open", "reveal"] },
  # Empty file
  { mime = "inode/x-empty", use = ["edit", "reveal"] },
  { mime = "application/json", use = ["edit", "reveal"] },
  { mime = "*/javascript", use = ["edit", "reveal"] },
  # Fallback
	{ name = "*", use = [ "open", "reveal" ] },
]

[plugin]
prepend_previewers = [
  # Archive previewer
  { mime = "application/*zip", run = "ouch" },
  { mime = "application/x-tar", run = "ouch" },
  { mime = "application/x-bzip2", run = "ouch" },
  { mime = "application/x-7z-compressed", run = "ouch" },
  { mime = "application/x-rar", run = "ouch" },
  { mime = "application/x-xz", run = "ouch" },
]
