require 'plugins.plugins'
require 'plugins.treesitter'
require 'plugins.colors'
require 'plugins.lualine'
-- require 'plugins.shade'
require 'plugins.autopairs'
require 'plugins.lsp'
require 'plugins.aerial'
require 'plugins.sessions'
require 'plugins.fidget'
require 'plugins.toggle_term'
require 'plugins.telescope'
require 'plugins.harpoon'
require 'plugins.gitsigns'
require 'plugins.trouble'
require 'plugins.crates'
