require 'plugins.plugins'
require 'plugins.treesitter'
require 'plugins.colors'
require 'plugins.lualine'
-- require 'plugins.spectare'
require 'plugins.lsp'
require 'plugins.fidget'
require 'plugins.toggle_term'
require 'plugins.telescope'
require 'plugins.harpoon'
require 'plugins.gitsigns'
require 'plugins.barbar'
require 'plugins.trouble'
